### ISSUE TITLE
Make error, No such file or directory: '.venv3/include/python3.5m/numpy'

### ISSUE THREAD

**Issue by erichahn** [leggedrobotics/any_ping_indicator#2]
After following the instructions I ran into an issue while running make.

Here's the make output log:
make
find any_ping_applet -type f -name *.pyc | xargs rm -rf
find any_ping_applet -type d -name __pycache__ | xargs rm -rf
rm -rf coverage
rm -f .coverage
rm -rf dist
rm -f MANIFEST
rm -rf any_ping_indicator.egg-info/
rm -rf /tmp/.any_ping.d/data/machine-index
rm -f ~/.any_ping_applet
rm -rf ./.venv/
virtualenv --python=python2.7 --system-site-packages .venv
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /home/scout/git/any_ping_indicator/.venv/bin/python2.7
Also creating executable in /home/scout/git/any_ping_indicator/.venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
.venv/bin/pip install nose==1.3.3 coverage==3.7.1 mock==1.0.1
Collecting nose==1.3.3
Collecting coverage==3.7.1
Collecting mock==1.0.1
Installing collected packages: nose, coverage, mock
  Found existing installation: nose 1.3.7
    Not uninstalling nose at /usr/lib/python2.7/dist-packages, outside environment /home/scout/git/any_ping_indicator/.venv
Successfully installed coverage-3.7.1 mock-1.0.1 nose-1.3.3
rm -rf ./.venv3/
virtualenv --python=python3 --system-site-packages .venv3
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/scout/git/any_ping_indicator/.venv3/bin/python3
Also creating executable in /home/scout/git/any_ping_indicator/.venv3/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
.venv3/bin/pip install nose==1.3.3 coverage==3.7.1 mock==1.0.1
Collecting nose==1.3.3
Collecting coverage==3.7.1
Collecting mock==1.0.1
Installing collected packages: nose, coverage, mock
Successfully installed coverage-3.7.1 mock-1.0.1 nose-1.3.3
export ANY_PING_HOME=/tmp/.any_ping.d; .venv/bin/nosetests

----------------------------------------------------------------------
Ran 0 tests in 0.001s

OK
export ANY_PING_HOME=/tmp/.any_ping.d; .venv3/bin/nosetests

----------------------------------------------------------------------
Ran 0 tests in 0.001s

OK
python2.7 setup.py sdist
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running sdist
running check
error: [Errno 2] No such file or directory: '.venv3/include/python3.5m/numpy'
Makefile:41: recipe for target 'sdist2' failed
make: *** [sdist2] Error 1

**Comment by samuelba** [comment]
thanks for reporting and sorry for the late reply. I will look into this.

**Comment by samuelba** [comment]
I tried to build and install in a fresh chroot environment and had no issues. What you could try, is if you remove everything Python 3 related from the Makefile.

Should than look something like this:

```
all: clean venv test sdist

clean:
	find any_ping_applet -type f -name *.pyc | xargs rm -rf
	find any_ping_applet -type d -name __pycache__ | xargs rm -rf
	rm -rf coverage
	rm -f .coverage
	rm -rf dist
	rm -f MANIFEST
	rm -rf any_ping_indicator.egg-info/
	rm -rf /tmp/.any_ping.d/data/machine-index
	rm -f ~/.any_ping_applet

venv2:
	rm -rf ./.venv/
	virtualenv --python=python2.7 --system-site-packages .venv
	.venv/bin/pip install nose==1.3.3 coverage==3.7.1 mock==1.0.1

venv: venv2

test2:
	export ANY_PING_HOME=/tmp/.any_ping.d; .venv/bin/nosetests

test: test2

#cover:
#	export ANY_PING_HOME=/tmp/.any_ping.d; .venv3/bin/nosetests --with-coverage --cover-branches --cover-package=any_ping_applet --cover-html --cover-html-dir=coverage

run:
	bin/any_ping_applet

sdist2: clean
	python2.7 setup.py sdist

sdist: sdist2

install: sdist2
	pip install dist/any_ping_indicator-*.tar.gz
	rm -rf dist

uninstall:
	pip uninstall any_ping_indicator
	rm -f /usr/share/applications/any_ping_applet.desktop
	rm -f ~/.any_ping_applet
	rm -rf /usr/share/any_ping_applet
```

**Comment by erichahn** [comment]
**That seems to help.**

I removed this repos folder off my local machine. Recloned it, modified the makefile per your comment and saw: make
find any_ping_applet -type f -name *.pyc | xargs rm -rf
find any_ping_applet -type d -name __pycache__ | xargs rm -rf
rm -rf coverage
rm -f .coverage
rm -rf dist
rm -f MANIFEST
rm -rf any_ping_indicator.egg-info/
rm -rf /tmp/.any_ping.d/data/machine-index
rm -f ~/.any_ping_applet
rm -rf ./.venv/
virtualenv --python=python2.7 --system-site-packages .venv
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /home/scout/git/any_ping_indicator/.venv/bin/python2.7
Also creating executable in /home/scout/git/any_ping_indicator/.venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
.venv/bin/pip install nose==1.3.3 coverage==3.7.1 mock==1.0.1
Collecting nose==1.3.3
Collecting coverage==3.7.1
Collecting mock==1.0.1
Installing collected packages: nose, coverage, mock
  Found existing installation: nose 1.3.7
    Not uninstalling nose at /usr/lib/python2.7/dist-packages, outside environment /home/scout/git/any_ping_indicator/.venv
Successfully installed coverage-3.7.1 mock-1.0.1 nose-1.3.3
export ANY_PING_HOME=/tmp/.any_ping.d; .venv/bin/nosetests

----------------------------------------------------------------------
Ran 0 tests in 0.001s

OK
python2.7 setup.py sdist
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running sdist
running check
warning: sdist: standard file not found: should have one of README, README.txt

reading manifest template 'MANIFEST.in'
writing manifest file 'MANIFEST'
creating any_ping_indicator-0.8
creating any_ping_indicator-0.8/any_ping_applet
creating any_ping_indicator-0.8/autostart
creating any_ping_indicator-0.8/bin
creating any_ping_indicator-0.8/img
creating any_ping_indicator-0.8/ui
making hard links in any_ping_indicator-0.8...
hard linking any_ping_applet.desktop -> any_ping_indicator-0.8
hard linking setup.py -> any_ping_indicator-0.8
hard linking any_ping_applet/__init__.py -> any_ping_indicator-0.8/any_ping_applet
hard linking any_ping_applet/about_dialog.py -> any_ping_indicator-0.8/any_ping_applet
hard linking any_ping_applet/config.py -> any_ping_indicator-0.8/any_ping_applet
hard linking any_ping_applet/indicator.py -> any_ping_indicator-0.8/any_ping_applet
hard linking any_ping_applet/ping_containers.py -> any_ping_indicator-0.8/any_ping_applet
hard linking any_ping_applet/ping_edit_dialog.py -> any_ping_indicator-0.8/any_ping_applet
hard linking any_ping_applet/ping_object.py -> any_ping_indicator-0.8/any_ping_applet
hard linking any_ping_applet/preferences_window.py -> any_ping_indicator-0.8/any_ping_applet
hard linking any_ping_applet/resource.py -> any_ping_indicator-0.8/any_ping_applet
hard linking any_ping_applet/theme.py -> any_ping_indicator-0.8/any_ping_applet
hard linking autostart/any_ping_applet.desktop -> any_ping_indicator-0.8/autostart
hard linking bin/any_ping_applet -> any_ping_indicator-0.8/bin
hard linking img/any_ping_indicator.png -> any_ping_indicator-0.8/img
hard linking img/any_ping_preferences.png -> any_ping_indicator-0.8/img
hard linking img/chuck_norris_1.jpg -> any_ping_indicator-0.8/img
hard linking img/chuck_norris_2.jpg -> any_ping_indicator-0.8/img
hard linking img/icon.png -> any_ping_indicator-0.8/img
hard linking img/icon.svg -> any_ping_indicator-0.8/img
hard linking img/icon.xcf -> any_ping_indicator-0.8/img
hard linking img/icon_green.svg -> any_ping_indicator-0.8/img
hard linking img/icon_grey.svg -> any_ping_indicator-0.8/img
hard linking img/icon_orange.svg -> any_ping_indicator-0.8/img
hard linking img/icon_raw.png -> any_ping_indicator-0.8/img
hard linking img/icon_red.svg -> any_ping_indicator-0.8/img
hard linking ui/ping_edit_dialog.glade -> any_ping_indicator-0.8/ui
hard linking ui/preferences_window.glade -> any_ping_indicator-0.8/ui
creating dist
Creating tar archive
removing 'any_ping_indicator-0.8' (and everything under it)

seems like it worked! Thanks for the helpful info.

**Comment by samuelba** [comment]
Glad to hear that.
